In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [8]:
#make a small model

X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [9]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [11]:
# we do standardization of the data
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

In [12]:
X = scalar.fit_transform(X)

In [15]:
X.shape

(768, 8)

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [81]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [21]:
model = Sequential()

model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(1, activation='sigmoid'))

c:\Users\Sanjog Bhalla\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [25]:
model.fit(X_train,y_train, epochs=100, batch_size=32, validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4431 - val_accuracy: 0.7727 - val_loss: 0.4984
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4412 - val_accuracy: 0.7727 - val_loss: 0.4990
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7866 - loss: 0.4399 - val_accuracy: 0.7662 - val_loss: 0.5003
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7915 - loss: 0.4388 - val_accuracy: 0.7727 - val_loss: 0.5004
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7899 - loss: 0.4378 - val_accuracy: 0.7662 - val_loss: 0.5015
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7915 - loss: 0.4362 - val_accuracy: 0.7597 - val_loss: 0.5023
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4349 - val_accuracy: 0.7727 - val_loss: 0.5040
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4339 - val_accuracy: 0.7662 - val_loss: 0.5050
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4329 - val_accuracy: 0.7662 - val_loss: 0.5033
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4318 - val_accuracy: 0.7727 - val_loss: 0.5020
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4319 - val_accuracy: 0.7727 - val_loss: 0.5035
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4306 - val_accuracy: 0.7727 - val_loss: 0.5050
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4293 - val_accuracy: 0.7727 - val_loss: 0.5061
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.7948 - loss: 0.4282 - val_accuracy: 0.7727 - val_loss: 0.5052
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7883 - loss: 0.4278 - val_accuracy: 0.7727 - val_loss: 0.5056
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7964 - loss: 0.4268 - val_accuracy: 0.7727 - val_loss: 0.5067
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7948 - loss: 0.4267 - val_accuracy: 0.7727 - val_loss: 0.5078
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4253 - val_accuracy: 0.7727 - val_loss: 0.5075
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4247 - val_accuracy: 0.7727 - val_loss: 0.5074
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4238 - val_accuracy: 0.7727 - val_loss: 0.5066
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4234 - val_accuracy: 0.7727 - val_loss: 0.5085
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7883 - loss: 0.4229 - val_accuracy: 0.7727 - val_loss: 0.5095
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7915 - loss: 0.4215 - val_accuracy: 0.7727 - val_loss: 0.5085
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4211 - val_accuracy: 0.7727 - val_loss: 0.5104
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7899 - loss: 0.4208 - val_accuracy: 0.7727 - val_loss: 0.5129
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4197 - val_accuracy: 0.7727 - val_loss: 0.5121
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4191 - val_accuracy: 0.7727 - val_loss: 0.5127
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4189 - val_accuracy: 0.7727 - val_loss: 0.5143
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4181 - val_accuracy: 0.7727 - val_loss: 0.5146
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4171 - val_accuracy: 0.7727 - val_loss: 0.5142
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4170 - val_accuracy: 0.7727 - val_loss: 0.5146
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4166 - val_accuracy: 0.7727 - val_loss: 0.5154
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4162 - val_accuracy: 0.7727 - val_loss: 0.5153
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4153 - val_accuracy: 0.7727 - val_loss: 0.5150
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4149 - val_accuracy: 0.7727 - val_loss: 0.5150
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4147 - val_accuracy: 0.7727 - val_loss: 0.5148
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7980 - loss: 0.4139 - val_accuracy: 0.7727 - val_loss: 0.5160
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.4131 - val_accuracy: 0.7662 - val_loss: 0.5157
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4131 - val_accuracy: 0.7727 - val_loss: 0.5138
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7964 - loss: 0.4126 - val_accuracy: 0.7662 - val_loss: 0.5140
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7964 - loss: 0.4116 - val_accuracy: 0.7662 - val_loss: 0.5136
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4116 - val_accuracy: 0.7662 - val_loss: 0.5134
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4114 - val_accuracy: 0.7662 - val_loss: 0.5120
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8013 - loss: 0.4105 - val_accuracy: 0.7662 - val_loss: 0.5151
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.7997 - loss: 0.4099 - val_accuracy: 0.7662 - val_loss: 0.5158
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8013 - loss: 0.4103 - val_accuracy: 0.7727 - val_loss: 0.5151
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8029 - loss: 0.4092 - val_accuracy: 0.7662 - val_loss: 0.5165
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7980 - loss: 0.4091 - val_accuracy: 0.7662 - val_loss: 0.5162
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8013 - loss: 0.4087 - val_accuracy: 0.7662 - val_loss: 0.5140
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8029 - loss: 0.4085 - val_accuracy: 0.7662 - val_loss: 0.5142
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8046 - loss: 0.4077 - val_accuracy: 0.7662 - val_loss: 0.5149
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8013 - loss: 0.4077 - val_accuracy: 0.7662 - val_loss: 0.5162
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7997 - loss: 0.4066 - val_accuracy: 0.7727 - val_loss: 0.5168
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4063 - val_accuracy: 0.7727 - val_loss: 0.5188
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7932 - loss: 0.4065 - val_accuracy: 0.7727 - val_loss: 0.5191
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7997 - loss: 0.4053 - val_accuracy: 0.7727 - val_loss: 0.5192
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4050 - val_accuracy: 0.7662 - val_loss: 0.5192
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4047 - val_accuracy: 0.7727 - val_loss: 0.5184
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4043 - val_accuracy: 0.7727 - val_loss: 0.5164
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4049 - val_accuracy: 0.7662 - val_loss: 0.5144
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4034 - val_accuracy: 0.7727 - val_loss: 0.5165
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4029 - val_accuracy: 0.7727 - val_loss: 0.5180
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4033 - val_accuracy: 0.7727 - val_loss: 0.5201
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4032 - val_accuracy: 0.7792 - val_loss: 0.5165
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8029 - loss: 0.4026 - val_accuracy: 0.7727 - val_loss: 0.5188
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8078 - loss: 0.4016 - val_accuracy: 0.7727 - val_loss: 0.5178
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7964 - loss: 0.4025 - val_accuracy: 0.7792 - val_loss: 0.5193
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7948 - loss: 0.4016 - val_accuracy: 0.7792 - val_loss: 0.5191
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.4003 - val_accuracy: 0.7727 - val_loss: 0.5211
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8094 - loss: 0.4000 - val_accuracy: 0.7727 - val_loss: 0.5215
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8094 - loss: 0.4001 - val_accuracy: 0.7662 - val_loss: 0.5238
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8078 - loss: 0.4003 - val_accuracy: 0.7662 - val_loss: 0.5214
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3997 - val_accuracy: 0.7662 - val_loss: 0.5229
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.3991 - val_accuracy: 0.7532 - val_loss: 0.5246
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8062 - loss: 0.3990 - val_accuracy: 0.7532 - val_loss: 0.5241
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.3982 - val_accuracy: 0.7662 - val_loss: 0.5216
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3983 - val_accuracy: 0.7597 - val_loss: 0.5188
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8111 - loss: 0.3980 - val_accuracy: 0.7662 - val_loss: 0.5199
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8127 - loss: 0.3975 - val_accuracy: 0.7597 - val_loss: 0.5219
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8111 - loss: 0.3968 - val_accuracy: 0.7662 - val_loss: 0.5194
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8078 - loss: 0.3964 - val_accuracy: 0.7662 - val_loss: 0.5222
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8078 - loss: 0.3966 - val_accuracy: 0.7597 - val_loss: 0.5230
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8046 - loss: 0.3969 - val_accuracy: 0.7727 - val_loss: 0.5222
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8094 - loss: 0.3954 - val_accuracy: 0.7662 - val_loss: 0.5232
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8078 - loss: 0.3953 - val_accuracy: 0.7597 - val_loss: 0.5250
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8094 - loss: 0.3953 - val_accuracy: 0.7597 - val_loss: 0.5222
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8127 - loss: 0.3945 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8111 - loss: 0.3942 - val_accuracy: 0.7597 - val_loss: 0.5227
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8127 - loss: 0.3945 - val_accuracy: 0.7468 - val_loss: 0.5243
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8160 - loss: 0.3939 - val_accuracy: 0.7532 - val_loss: 0.5226
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3933 - val_accuracy: 0.7532 - val_loss: 0.5245
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8143 - loss: 0.3933 - val_accuracy: 0.7468 - val_loss: 0.5274
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8160 - loss: 0.3931 - val_accuracy: 0.7468 - val_loss: 0.5253
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8176 - loss: 0.3926 - val_accuracy: 0.7468 - val_loss: 0.5246
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8176 - loss: 0.3927 - val_accuracy: 0.7468 - val_loss: 0.5238
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3918 - val_accuracy: 0.7597 - val_loss: 0.5227
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8127 - loss: 0.3915 - val_accuracy: 0.7597 - val_loss: 0.5217
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8176 - loss: 0.3914 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3910 - val_accuracy: 0.7532 - val_loss: 0.5221
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.3906 - val_accuracy: 0.7532 - val_loss: 0.5221

In [26]:
# 1. how to select appropriate optimizer
# 2. No of nodes in the hidden layer
# 3. how to select number of hidden layer
# 4. All in all one model

In [27]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (3.13.1)
Requirement already satisfied: packaging in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (1.76.0)
Requirement already satisfied: protobuf in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras-tuner) (5.29.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (2.3.1)
Requirement already satisfied: numpy in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (3.12.1)
Requirement already satisfied: optree in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from requests->keras-tuner) (2025.8.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\sanjog bhalla\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.0)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner

   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   -------------------- ------------------- 1/2 [keras-tuner]
   ---------------------------------------- 2/2 [keras-tuner]

Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [29]:
import keras_tuner as kt

In [36]:
def build_model(hp):
    
    model = Sequential()
    
    model.add(Dense(32, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))
    
    optimizer = hp.Choice('optimizer', values=['adam','sgd', 'rmsprop','adagrad'])
    
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    
    return model

In [37]:
# Tuner Object

tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5)

Reloading Tuner from .\untitled_project\tuner0.json

In [38]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

In [41]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [47]:
model = tuner.get_best_models(num_models=1)[0]

c:\Users\Sanjog Bhalla\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\Sanjog Bhalla\anaconda3\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [48]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.fit(X_train,y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.7443 - loss: 0.5238 - val_accuracy: 0.7532 - val_loss: 0.5385
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7557 - loss: 0.5022 - val_accuracy: 0.7403 - val_loss: 0.5289
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7557 - loss: 0.4883 - val_accuracy: 0.7403 - val_loss: 0.5217
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7671 - loss: 0.4780 - val_accuracy: 0.7532 - val_loss: 0.5195
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.7720 - loss: 0.4708 - val_accuracy: 0.7597 - val_loss: 0.5157
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7720 - loss: 0.4652 - val_accuracy: 0.7532 - val_loss: 0.5135
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7736 - loss: 0.4614 - val_accuracy: 0.7532 - val_loss: 0.5108
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7736 - loss: 0.4575 - val_accuracy: 0.7597 - val_loss: 0.5102
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7720 - loss: 0.4545 - val_accuracy: 0.7532 - val_loss: 0.5109
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7752 - loss: 0.4521 - val_accuracy: 0.7597 - val_loss: 0.5098
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7752 - loss: 0.4498 - val_accuracy: 0.7597 - val_loss: 0.5110
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7752 - loss: 0.4476 - val_accuracy: 0.7532 - val_loss: 0.5119
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7801 - loss: 0.4460 - val_accuracy: 0.7532 - val_loss: 0.5120
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7834 - loss: 0.4439 - val_accuracy: 0.7532 - val_loss: 0.5119
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7834 - loss: 0.4429 - val_accuracy: 0.7532 - val_loss: 0.5129
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7818 - loss: 0.4418 - val_accuracy: 0.7468 - val_loss: 0.5136
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7866 - loss: 0.4406 - val_accuracy: 0.7468 - val_loss: 0.5127
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7801 - loss: 0.4389 - val_accuracy: 0.7532 - val_loss: 0.5161
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4376 - val_accuracy: 0.7468 - val_loss: 0.5176
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4366 - val_accuracy: 0.7403 - val_loss: 0.5181
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4353 - val_accuracy: 0.7597 - val_loss: 0.5153
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4346 - val_accuracy: 0.7532 - val_loss: 0.5124
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4335 - val_accuracy: 0.7597 - val_loss: 0.5129
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4320 - val_accuracy: 0.7727 - val_loss: 0.5139
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4315 - val_accuracy: 0.7532 - val_loss: 0.5150
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4302 - val_accuracy: 0.7532 - val_loss: 0.5168
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7883 - loss: 0.4290 - val_accuracy: 0.7532 - val_loss: 0.5167
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4282 - val_accuracy: 0.7532 - val_loss: 0.5174
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4272 - val_accuracy: 0.7532 - val_loss: 0.5168
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7850 - loss: 0.4265 - val_accuracy: 0.7532 - val_loss: 0.5184
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7883 - loss: 0.4257 - val_accuracy: 0.7532 - val_loss: 0.5178
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7850 - loss: 0.4248 - val_accuracy: 0.7532 - val_loss: 0.5165
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7899 - loss: 0.4252 - val_accuracy: 0.7532 - val_loss: 0.5179
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7915 - loss: 0.4232 - val_accuracy: 0.7597 - val_loss: 0.5200
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7899 - loss: 0.4224 - val_accuracy: 0.7532 - val_loss: 0.5206
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4220 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4213 - val_accuracy: 0.7662 - val_loss: 0.5236
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4207 - val_accuracy: 0.7532 - val_loss: 0.5247
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4196 - val_accuracy: 0.7662 - val_loss: 0.5241
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4192 - val_accuracy: 0.7662 - val_loss: 0.5251
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4188 - val_accuracy: 0.7468 - val_loss: 0.5285
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4175 - val_accuracy: 0.7468 - val_loss: 0.5275
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7964 - loss: 0.4174 - val_accuracy: 0.7403 - val_loss: 0.5296
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7915 - loss: 0.4171 - val_accuracy: 0.7468 - val_loss: 0.5302
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7915 - loss: 0.4155 - val_accuracy: 0.7403 - val_loss: 0.5296
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4151 - val_accuracy: 0.7403 - val_loss: 0.5319
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7932 - loss: 0.4145 - val_accuracy: 0.7403 - val_loss: 0.5294
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7915 - loss: 0.4137 - val_accuracy: 0.7597 - val_loss: 0.5295
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7932 - loss: 0.4143 - val_accuracy: 0.7338 - val_loss: 0.5303
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7915 - loss: 0.4138 - val_accuracy: 0.7403 - val_loss: 0.5321
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7964 - loss: 0.4121 - val_accuracy: 0.7403 - val_loss: 0.5295
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7964 - loss: 0.4120 - val_accuracy: 0.7662 - val_loss: 0.5280
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4112 - val_accuracy: 0.7403 - val_loss: 0.5310
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4109 - val_accuracy: 0.7338 - val_loss: 0.5335
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4102 - val_accuracy: 0.7338 - val_loss: 0.5322
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4098 - val_accuracy: 0.7597 - val_loss: 0.5313
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4098 - val_accuracy: 0.7532 - val_loss: 0.5291
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4091 - val_accuracy: 0.7597 - val_loss: 0.5311
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4087 - val_accuracy: 0.7403 - val_loss: 0.5317
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4084 - val_accuracy: 0.7403 - val_loss: 0.5309
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4075 - val_accuracy: 0.7468 - val_loss: 0.5364
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7964 - loss: 0.4071 - val_accuracy: 0.7468 - val_loss: 0.5343
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4065 - val_accuracy: 0.7403 - val_loss: 0.5345
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7948 - loss: 0.4061 - val_accuracy: 0.7468 - val_loss: 0.5367
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7980 - loss: 0.4058 - val_accuracy: 0.7468 - val_loss: 0.5359
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7997 - loss: 0.4054 - val_accuracy: 0.7468 - val_loss: 0.5337
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7997 - loss: 0.4053 - val_accuracy: 0.7468 - val_loss: 0.5318
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7980 - loss: 0.4047 - val_accuracy: 0.7468 - val_loss: 0.5333
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7980 - loss: 0.4042 - val_accuracy: 0.7403 - val_loss: 0.5326
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4039 - val_accuracy: 0.7403 - val_loss: 0.5346
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4033 - val_accuracy: 0.7403 - val_loss: 0.5361
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4032 - val_accuracy: 0.7468 - val_loss: 0.5343
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4030 - val_accuracy: 0.7403 - val_loss: 0.5369
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4024 - val_accuracy: 0.7403 - val_loss: 0.5357
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4021 - val_accuracy: 0.7532 - val_loss: 0.5335
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8046 - loss: 0.4017 - val_accuracy: 0.7532 - val_loss: 0.5340
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8046 - loss: 0.4014 - val_accuracy: 0.7532 - val_loss: 0.5345
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8094 - loss: 0.4010 - val_accuracy: 0.7532 - val_loss: 0.5348
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8143 - loss: 0.4006 - val_accuracy: 0.7468 - val_loss: 0.5384
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3999 - val_accuracy: 0.7468 - val_loss: 0.5385
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8143 - loss: 0.4000 - val_accuracy: 0.7403 - val_loss: 0.5420
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8111 - loss: 0.3995 - val_accuracy: 0.7468 - val_loss: 0.5399
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8094 - loss: 0.3996 - val_accuracy: 0.7403 - val_loss: 0.5400
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.3994 - val_accuracy: 0.7468 - val_loss: 0.5386
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.3986 - val_accuracy: 0.7468 - val_loss: 0.5384
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.3980 - val_accuracy: 0.7403 - val_loss: 0.5390
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.3980 - val_accuracy: 0.7468 - val_loss: 0.5393
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.3978 - val_accuracy: 0.7403 - val_loss: 0.5387
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.3967 - val_accuracy: 0.7403 - val_loss: 0.5380
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.3967 - val_accuracy: 0.7403 - val_loss: 0.5393
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.3966 - val_accuracy: 0.7338 - val_loss: 0.5416
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.3967 - val_accuracy: 0.7468 - val_loss: 0.5373
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8143 - loss: 0.3959 - val_accuracy: 0.7403 - val_loss: 0.5401
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8094 - loss: 0.3956 - val_accuracy: 0.7468 - val_loss: 0.5399

In [54]:
# No of Neurons

def build_model(hp):
    
    model = Sequential()
    
    units = hp.Int('units', min_value=8, max_value=128, step=8)
    
    model.add(Dense(units=units, activation='relu', input_dim=8))
    model.add(Dense(1, activation='sigmoid'))
    
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

In [55]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=5, directory='my_dir')

In [56]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 04s]
val_accuracy: 0.7272727489471436

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 19s

In [57]:
tuner.get_best_hyperparameters()[0].values

{'units': 104}

In [59]:
model = tuner.get_best_models(num_models=1)[0]

In [60]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 104)            │           936 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           105 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,041 (4.07 KB)

 Trainable params: 1,041 (4.07 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.fit(X_train,y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.7752 - loss: 0.4768 - val_accuracy: 0.7727 - val_loss: 0.4982
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4616 - val_accuracy: 0.7597 - val_loss: 0.4970
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4555 - val_accuracy: 0.7727 - val_loss: 0.4956
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4501 - val_accuracy: 0.7597 - val_loss: 0.4982
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4452 - val_accuracy: 0.7727 - val_loss: 0.5001
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7818 - loss: 0.4420 - val_accuracy: 0.7597 - val_loss: 0.5037
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7883 - loss: 0.4393 - val_accuracy: 0.7597 - val_loss: 0.5048
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7899 - loss: 0.4366 - val_accuracy: 0.7597 - val_loss: 0.5073
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7964 - loss: 0.4347 - val_accuracy: 0.7597 - val_loss: 0.5082
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4333 - val_accuracy: 0.7597 - val_loss: 0.5090
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4314 - val_accuracy: 0.7662 - val_loss: 0.5089
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7932 - loss: 0.4302 - val_accuracy: 0.7597 - val_loss: 0.5109
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4286 - val_accuracy: 0.7597 - val_loss: 0.5137
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4266 - val_accuracy: 0.7468 - val_loss: 0.5177
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4247 - val_accuracy: 0.7532 - val_loss: 0.5161
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4240 - val_accuracy: 0.7532 - val_loss: 0.5174
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4239 - val_accuracy: 0.7532 - val_loss: 0.5169
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7883 - loss: 0.4216 - val_accuracy: 0.7532 - val_loss: 0.5181
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7883 - loss: 0.4203 - val_accuracy: 0.7468 - val_loss: 0.5227
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7948 - loss: 0.4197 - val_accuracy: 0.7403 - val_loss: 0.5263
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4183 - val_accuracy: 0.7532 - val_loss: 0.5223
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4179 - val_accuracy: 0.7597 - val_loss: 0.5208
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4162 - val_accuracy: 0.7532 - val_loss: 0.5224
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8013 - loss: 0.4149 - val_accuracy: 0.7468 - val_loss: 0.5245
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4145 - val_accuracy: 0.7532 - val_loss: 0.5230
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4143 - val_accuracy: 0.7468 - val_loss: 0.5258
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4134 - val_accuracy: 0.7532 - val_loss: 0.5224
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4121 - val_accuracy: 0.7532 - val_loss: 0.5256
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8029 - loss: 0.4130 - val_accuracy: 0.7597 - val_loss: 0.5272
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - accuracy: 0.7997 - loss: 0.4114 - val_accuracy: 0.7532 - val_loss: 0.5333
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4100 - val_accuracy: 0.7468 - val_loss: 0.5316
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4092 - val_accuracy: 0.7403 - val_loss: 0.5339
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4082 - val_accuracy: 0.7468 - val_loss: 0.5303
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4073 - val_accuracy: 0.7597 - val_loss: 0.5328
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4071 - val_accuracy: 0.7468 - val_loss: 0.5339
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4066 - val_accuracy: 0.7468 - val_loss: 0.5316
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4066 - val_accuracy: 0.7532 - val_loss: 0.5331
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4053 - val_accuracy: 0.7468 - val_loss: 0.5319
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4044 - val_accuracy: 0.7468 - val_loss: 0.5352
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4034 - val_accuracy: 0.7532 - val_loss: 0.5351
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8078 - loss: 0.4029 - val_accuracy: 0.7532 - val_loss: 0.5340
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8062 - loss: 0.4020 - val_accuracy: 0.7532 - val_loss: 0.5353
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8078 - loss: 0.4017 - val_accuracy: 0.7532 - val_loss: 0.5349
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8062 - loss: 0.4015 - val_accuracy: 0.7338 - val_loss: 0.5379
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.4009 - val_accuracy: 0.7338 - val_loss: 0.5395
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.3999 - val_accuracy: 0.7468 - val_loss: 0.5429
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8078 - loss: 0.3990 - val_accuracy: 0.7403 - val_loss: 0.5420
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.3984 - val_accuracy: 0.7403 - val_loss: 0.5424
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3988 - val_accuracy: 0.7403 - val_loss: 0.5426
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.3978 - val_accuracy: 0.7403 - val_loss: 0.5436
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.3968 - val_accuracy: 0.7403 - val_loss: 0.5435
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8094 - loss: 0.3978 - val_accuracy: 0.7468 - val_loss: 0.5445
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8143 - loss: 0.3958 - val_accuracy: 0.7338 - val_loss: 0.5434
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8143 - loss: 0.3939 - val_accuracy: 0.7338 - val_loss: 0.5444
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8160 - loss: 0.3949 - val_accuracy: 0.7338 - val_loss: 0.5477
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8029 - loss: 0.3942 - val_accuracy: 0.7338 - val_loss: 0.5520
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.3969 - val_accuracy: 0.7273 - val_loss: 0.5534
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8257 - loss: 0.3933 - val_accuracy: 0.7338 - val_loss: 0.5511
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.3926 - val_accuracy: 0.7338 - val_loss: 0.5497
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.3910 - val_accuracy: 0.7338 - val_loss: 0.5496
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8176 - loss: 0.3905 - val_accuracy: 0.7273 - val_loss: 0.5508
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8127 - loss: 0.3900 - val_accuracy: 0.7273 - val_loss: 0.5499
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8094 - loss: 0.3896 - val_accuracy: 0.7338 - val_loss: 0.5487
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8111 - loss: 0.3895 - val_accuracy: 0.7338 - val_loss: 0.5511
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8225 - loss: 0.3895 - val_accuracy: 0.7338 - val_loss: 0.5494
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8160 - loss: 0.3889 - val_accuracy: 0.7338 - val_loss: 0.5479
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8241 - loss: 0.3881 - val_accuracy: 0.7338 - val_loss: 0.5502
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3877 - val_accuracy: 0.7338 - val_loss: 0.5528
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3876 - val_accuracy: 0.7208 - val_loss: 0.5521
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3863 - val_accuracy: 0.7338 - val_loss: 0.5500
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3871 - val_accuracy: 0.7143 - val_loss: 0.5529
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3851 - val_accuracy: 0.7208 - val_loss: 0.5468
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3862 - val_accuracy: 0.7338 - val_loss: 0.5472
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.3848 - val_accuracy: 0.7143 - val_loss: 0.5537
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3838 - val_accuracy: 0.7273 - val_loss: 0.5512
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8274 - loss: 0.3830 - val_accuracy: 0.7143 - val_loss: 0.5555
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8274 - loss: 0.3835 - val_accuracy: 0.7208 - val_loss: 0.5565
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8274 - loss: 0.3824 - val_accuracy: 0.7273 - val_loss: 0.5551
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8225 - loss: 0.3816 - val_accuracy: 0.7208 - val_loss: 0.5508
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3827 - val_accuracy: 0.7338 - val_loss: 0.5505
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3817 - val_accuracy: 0.7338 - val_loss: 0.5503
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3809 - val_accuracy: 0.7208 - val_loss: 0.5489
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3800 - val_accuracy: 0.7208 - val_loss: 0.5533
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3806 - val_accuracy: 0.7273 - val_loss: 0.5548
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.3790 - val_accuracy: 0.7338 - val_loss: 0.5571
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3785 - val_accuracy: 0.7208 - val_loss: 0.5563
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8322 - loss: 0.3779 - val_accuracy: 0.7208 - val_loss: 0.5542
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.3777 - val_accuracy: 0.7208 - val_loss: 0.5514
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8274 - loss: 0.3785 - val_accuracy: 0.7208 - val_loss: 0.5534
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8290 - loss: 0.3769 - val_accuracy: 0.7273 - val_loss: 0.5551
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8274 - loss: 0.3765 - val_accuracy: 0.7208 - val_loss: 0.5518
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8322 - loss: 0.3760 - val_accuracy: 0.7208 - val_loss: 0.5522
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8192 - loss: 0.3786 - val_accuracy: 0.7338 - val_loss: 0.5548
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8306 - loss: 0.3759 - val_accuracy: 0.7338 - val_loss: 0.5558

In [62]:
# How to select number of hidden layers

def build_model(hp):
    
    model = Sequential()
    
    model.add(Dense(72, activation='relu', input_dim=8))
    
    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        
        model.add(Dense(72, activation='relu'))
        
    model.add(Dense(1, activation='sigmoid'))
    
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

In [63]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=3, directory='my_dir_num_layers', project_name='num_layers')

c:\Users\Sanjog Bhalla\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [65]:
tuner.search(X_train,y_train, epochs=5, validation_data=(X_test,y_test))

Trial 3 Complete [00h 00m 09s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 48s

In [66]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2}

In [67]:
model = tuner.get_best_models(num_models=1)[0]

c:\Users\Sanjog Bhalla\anaconda3\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 18 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [68]:
model.fit(X_train,y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 0.7899 - loss: 0.4409 - val_accuracy: 0.7597 - val_loss: 0.5308
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4221 - val_accuracy: 0.7597 - val_loss: 0.5337
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4190 - val_accuracy: 0.7468 - val_loss: 0.5417
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8046 - loss: 0.4119 - val_accuracy: 0.7468 - val_loss: 0.5489
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8176 - loss: 0.4039 - val_accuracy: 0.7468 - val_loss: 0.5600
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8160 - loss: 0.3971 - val_accuracy: 0.7338 - val_loss: 0.5545
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8160 - loss: 0.3908 - val_accuracy: 0.7273 - val_loss: 0.5710
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.8257 - loss: 0.3840 - val_accuracy: 0.7468 - val_loss: 0.5541
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8339 - loss: 0.3802 - val_accuracy: 0.7338 - val_loss: 0.5604
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3707 - val_accuracy: 0.7532 - val_loss: 0.5649
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3717 - val_accuracy: 0.7078 - val_loss: 0.6143
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8257 - loss: 0.3691 - val_accuracy: 0.7532 - val_loss: 0.5808
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8388 - loss: 0.3571 - val_accuracy: 0.7403 - val_loss: 0.5824
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8371 - loss: 0.3512 - val_accuracy: 0.7468 - val_loss: 0.5930
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3539 - val_accuracy: 0.7532 - val_loss: 0.5799
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3511 - val_accuracy: 0.7468 - val_loss: 0.5859
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8453 - loss: 0.3419 - val_accuracy: 0.7013 - val_loss: 0.6232
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8485 - loss: 0.3371 - val_accuracy: 0.7208 - val_loss: 0.6082
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8550 - loss: 0.3263 - val_accuracy: 0.7403 - val_loss: 0.6022
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8550 - loss: 0.3227 - val_accuracy: 0.7338 - val_loss: 0.6157
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8567 - loss: 0.3115 - val_accuracy: 0.7013 - val_loss: 0.6485
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3094 - val_accuracy: 0.7078 - val_loss: 0.6412
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8697 - loss: 0.3040 - val_accuracy: 0.7273 - val_loss: 0.6424
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8762 - loss: 0.2896 - val_accuracy: 0.7338 - val_loss: 0.6497
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8811 - loss: 0.2880 - val_accuracy: 0.7013 - val_loss: 0.6773
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8827 - loss: 0.2792 - val_accuracy: 0.7403 - val_loss: 0.6796
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8844 - loss: 0.2764 - val_accuracy: 0.7078 - val_loss: 0.6679
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2659 - val_accuracy: 0.7273 - val_loss: 0.6861
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8941 - loss: 0.2586 - val_accuracy: 0.7013 - val_loss: 0.7113
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9055 - loss: 0.2576 - val_accuracy: 0.7143 - val_loss: 0.7078
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8990 - loss: 0.2522 - val_accuracy: 0.7078 - val_loss: 0.7421
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8990 - loss: 0.2419 - val_accuracy: 0.7403 - val_loss: 0.6990
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8941 - loss: 0.2451 - val_accuracy: 0.7208 - val_loss: 0.7515
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.2344 - val_accuracy: 0.6948 - val_loss: 0.7484
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9007 - loss: 0.2331 - val_accuracy: 0.7013 - val_loss: 0.8300
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9137 - loss: 0.2174 - val_accuracy: 0.6948 - val_loss: 0.8290
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9186 - loss: 0.2135 - val_accuracy: 0.7013 - val_loss: 0.7859
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9267 - loss: 0.2051 - val_accuracy: 0.7078 - val_loss: 0.7927
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9300 - loss: 0.1890 - val_accuracy: 0.7013 - val_loss: 0.8306
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9218 - loss: 0.1896 - val_accuracy: 0.7013 - val_loss: 0.8665
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9300 - loss: 0.1817 - val_accuracy: 0.7208 - val_loss: 0.8387
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9446 - loss: 0.1775 - val_accuracy: 0.7013 - val_loss: 0.9080
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9463 - loss: 0.1699 - val_accuracy: 0.6883 - val_loss: 0.8310
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9397 - loss: 0.1652 - val_accuracy: 0.6883 - val_loss: 0.9171
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.9414 - loss: 0.1564 - val_accuracy: 0.6753 - val_loss: 0.9840
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9463 - loss: 0.1574 - val_accuracy: 0.7013 - val_loss: 0.9233
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9479 - loss: 0.1520 - val_accuracy: 0.6948 - val_loss: 0.9019
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9528 - loss: 0.1412 - val_accuracy: 0.6753 - val_loss: 0.9916
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9544 - loss: 0.1336 - val_accuracy: 0.6883 - val_loss: 1.0095
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9674 - loss: 0.1328 - val_accuracy: 0.7143 - val_loss: 0.9623
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9528 - loss: 0.1336 - val_accuracy: 0.6818 - val_loss: 1.0536
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9577 - loss: 0.1258 - val_accuracy: 0.7013 - val_loss: 1.0946
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9593 - loss: 0.1308 - val_accuracy: 0.6948 - val_loss: 1.0892
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.9528 - loss: 0.1382 - val_accuracy: 0.6948 - val_loss: 1.0259
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9658 - loss: 0.1058 - val_accuracy: 0.6753 - val_loss: 1.1125
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9707 - loss: 0.0967 - val_accuracy: 0.7013 - val_loss: 1.0858
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9756 - loss: 0.0977 - val_accuracy: 0.6818 - val_loss: 1.0943
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9837 - loss: 0.0878 - val_accuracy: 0.6883 - val_loss: 1.2016
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9772 - loss: 0.0850 - val_accuracy: 0.6883 - val_loss: 1.1139
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0823 - val_accuracy: 0.7078 - val_loss: 1.1543
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0762 - val_accuracy: 0.7013 - val_loss: 1.2329
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9788 - loss: 0.0816 - val_accuracy: 0.7013 - val_loss: 1.2548
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.9723 - loss: 0.0961 - val_accuracy: 0.6818 - val_loss: 1.1908
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9788 - loss: 0.0723 - val_accuracy: 0.6883 - val_loss: 1.2375
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9902 - loss: 0.0588 - val_accuracy: 0.6883 - val_loss: 1.1947
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9902 - loss: 0.0524 - val_accuracy: 0.6883 - val_loss: 1.2791
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9919 - loss: 0.0511 - val_accuracy: 0.6883 - val_loss: 1.3112
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0552 - val_accuracy: 0.6818 - val_loss: 1.3481
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9935 - loss: 0.0491 - val_accuracy: 0.6948 - val_loss: 1.3111
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9919 - loss: 0.0521 - val_accuracy: 0.7013 - val_loss: 1.3592
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9853 - loss: 0.0715 - val_accuracy: 0.6948 - val_loss: 1.3836
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0641 - val_accuracy: 0.6948 - val_loss: 1.4095
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0613 - val_accuracy: 0.6818 - val_loss: 1.3842
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9951 - loss: 0.0431 - val_accuracy: 0.6883 - val_loss: 1.3879
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9935 - loss: 0.0366 - val_accuracy: 0.6753 - val_loss: 1.4267
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9951 - loss: 0.0320 - val_accuracy: 0.6883 - val_loss: 1.4592
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9984 - loss: 0.0294 - val_accuracy: 0.6948 - val_loss: 1.4708
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0260 - val_accuracy: 0.6818 - val_loss: 1.4846
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0258 - val_accuracy: 0.6883 - val_loss: 1.5225
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9984 - loss: 0.0300 - val_accuracy: 0.6753 - val_loss: 1.6635
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0252 - val_accuracy: 0.6948 - val_loss: 1.5644
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0230 - val_accuracy: 0.6753 - val_loss: 1.6347
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0221 - val_accuracy: 0.6883 - val_loss: 1.5676
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9902 - loss: 0.0566 - val_accuracy: 0.6753 - val_loss: 1.5987
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9902 - loss: 0.0396 - val_accuracy: 0.7143 - val_loss: 1.5541
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.9951 - loss: 0.0360 - val_accuracy: 0.6948 - val_loss: 1.6977
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 1.0000 - loss: 0.0267 - val_accuracy: 0.7013 - val_loss: 1.6589
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 1.0000 - loss: 0.0211 - val_accuracy: 0.6948 - val_loss: 1.7237
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9984 - loss: 0.0221 - val_accuracy: 0.7078 - val_loss: 1.7169
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 1.0000 - loss: 0.0183 - val_accuracy: 0.6818 - val_loss: 1.6991
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9967 - loss: 0.0197 - val_accuracy: 0.6948 - val_loss: 1.7674
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 1.0000 - loss: 0.0143 - val_accuracy: 0.6883 - val_loss: 1.7585
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0135 - val_accuracy: 0.6818 - val_loss: 1.8115
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9984 - loss: 0.0133 - val_accuracy: 0.6948 - val_loss: 1.7978

In [104]:
def build_model(hp):
    
    model = Sequential()
    
    counter = 0
    
    for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
        
        if counter == 0:
            
            model.add(Dense(
                hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                activation=hp.Choice('activation' + str(i), values=['relu','tanh','sigmoid']),
                input_dim=8
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
            
        else:
            
            model.add(Dense(
                hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                activation=hp.Choice('activation' + str(i), values=['relu','tanh','sigmoid'])
            ))
            model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
        
        counter += 1
        
    model.add(Dense(1, activation='sigmoid'))  # Output layer after loop
    
    model.compile(
        loss='binary_crossentropy', 
        optimizer=hp.Choice('optimizer', values=['adam','sgd', 'rmsprop','adagrad']), 
        metrics=['accuracy']
    )
    
    return model

In [105]:
tuner = kt.RandomSearch(build_model, objective='val_accuracy', max_trials=3, directory='final_dir12', project_name='final2')

In [106]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test,y_test))
print(tuner.results_summary())  # All trials shown here

Trial 3 Complete [00h 00m 06s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.7272727489471436
Total elapsed time: 00h 00m 16s
Results summary
Results in final_dir12\final2
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
num_layers: 2
units0: 80
activation0: relu
dropout0: 0.5
optimizer: adam
units1: 8
activation1: relu
dropout1: 0.0
Score: 0.7272727489471436

Trial 1 summary
Hyperparameters:
num_layers: 7
units0: 16
activation0: relu
dropout0: 0.2
optimizer: adagrad
units1: 96
activation1: tanh
dropout1: 0.2
units2: 8
activation2: relu
dropout2: 0.0
units3: 8
activation3: relu
dropout3: 0.0
units4: 8
activation4: relu
dropout4: 0.0
units5: 8
activation5: relu
dropout5: 0.0
units6: 8
activation6: relu
dropout6: 0.0
Score: 0.6428571343421936

Trial 2 summary
Hyperparameters:
num_layers: 7
units0: 64
activation0: tanh
dropout0: 0.8
optimizer: rmsprop
units1: 40
activation1: tanh
dropout1: 0.7
units2: 48
activation2: tanh
dropout2: 0.1
units3: 88
activation3: sigmoid
dropout3: 0.3
units4: 120
activation4: tanh
dropout4: 0.5
units5: 56
activation5: tanh
dropout5: 0.6
units6: 48
activation6: tanh
dropout6: 0.0
Score: 0.6428571343421936
None

In [107]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 80,
 'activation0': 'relu',
 'dropout0': 0.5,
 'optimizer': 'adam',
 'units1': 8,
 'activation1': 'relu',
 'dropout1': 0.0}

In [108]:
model = tuner.get_best_models(num_models=1)[0]

c:\Users\Sanjog Bhalla\anaconda3\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [109]:
model.fit(X_train,y_train, epochs=200, initial_epoch=6, validation_data=(X_test,y_test))

Epoch 7/200

20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - accuracy: 0.7573 - loss: 0.5078 - val_accuracy: 0.7468 - val_loss: 0.5240
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7443 - loss: 0.4871 - val_accuracy: 0.7338 - val_loss: 0.5132
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7687 - loss: 0.4905 - val_accuracy: 0.7468 - val_loss: 0.5104
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7671 - loss: 0.4624 - val_accuracy: 0.7727 - val_loss: 0.5104
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4762 - val_accuracy: 0.7597 - val_loss: 0.5089
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7801 - loss: 0.4742 - val_accuracy: 0.7597 - val_loss: 0.5072
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.7834 - loss: 0.4658 - val_accuracy: 0.7532 - val_loss: 0.5099
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7720 - loss: 0.4637 - val_accuracy: 0.7597 - val_loss: 0.5096
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7752 - loss: 0.4577 - val_accuracy: 0.7597 - val_loss: 0.5106
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7752 - loss: 0.4672 - val_accuracy: 0.7597 - val_loss: 0.5132
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8062 - loss: 0.4502 - val_accuracy: 0.7532 - val_loss: 0.5145
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7866 - loss: 0.4663 - val_accuracy: 0.7532 - val_loss: 0.5159
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.7687 - loss: 0.4632 - val_accuracy: 0.7597 - val_loss: 0.5168
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7801 - loss: 0.4554 - val_accuracy: 0.7597 - val_loss: 0.5169
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.7818 - loss: 0.4491 - val_accuracy: 0.7597 - val_loss: 0.5177
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7704 - loss: 0.4668 - val_accuracy: 0.7597 - val_loss: 0.5202
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7671 - loss: 0.4644 - val_accuracy: 0.7597 - val_loss: 0.5191
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4565 - val_accuracy: 0.7727 - val_loss: 0.5173
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - accuracy: 0.7720 - loss: 0.4569 - val_accuracy: 0.7727 - val_loss: 0.5183
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7818 - loss: 0.4605 - val_accuracy: 0.7727 - val_loss: 0.5186
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7785 - loss: 0.4526 - val_accuracy: 0.7792 - val_loss: 0.5203
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7818 - loss: 0.4533 - val_accuracy: 0.7727 - val_loss: 0.5186
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7834 - loss: 0.4468 - val_accuracy: 0.7792 - val_loss: 0.5179
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7850 - loss: 0.4529 - val_accuracy: 0.7792 - val_loss: 0.5152
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8078 - loss: 0.4433 - val_accuracy: 0.7727 - val_loss: 0.5193
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7915 - loss: 0.4392 - val_accuracy: 0.7597 - val_loss: 0.5211
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8013 - loss: 0.4350 - val_accuracy: 0.7532 - val_loss: 0.5278
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4363 - val_accuracy: 0.7532 - val_loss: 0.5292
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4395 - val_accuracy: 0.7597 - val_loss: 0.5290
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4468 - val_accuracy: 0.7662 - val_loss: 0.5302
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4519 - val_accuracy: 0.7857 - val_loss: 0.5277
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4371 - val_accuracy: 0.7857 - val_loss: 0.5276
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4447 - val_accuracy: 0.7727 - val_loss: 0.5292
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4302 - val_accuracy: 0.7727 - val_loss: 0.5316
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4486 - val_accuracy: 0.7727 - val_loss: 0.5318
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.4277 - val_accuracy: 0.7727 - val_loss: 0.5321
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7834 - loss: 0.4385 - val_accuracy: 0.7727 - val_loss: 0.5329
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.7899 - loss: 0.4389 - val_accuracy: 0.7727 - val_loss: 0.5339
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4400 - val_accuracy: 0.7792 - val_loss: 0.5342
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4387 - val_accuracy: 0.7857 - val_loss: 0.5337
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4288 - val_accuracy: 0.7857 - val_loss: 0.5347
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4262 - val_accuracy: 0.7792 - val_loss: 0.5349
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4241 - val_accuracy: 0.7792 - val_loss: 0.5365
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4215 - val_accuracy: 0.7727 - val_loss: 0.5386
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4381 - val_accuracy: 0.7662 - val_loss: 0.5396
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4345 - val_accuracy: 0.7727 - val_loss: 0.5388
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7899 - loss: 0.4412 - val_accuracy: 0.7662 - val_loss: 0.5402
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7883 - loss: 0.4304 - val_accuracy: 0.7662 - val_loss: 0.5420
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7883 - loss: 0.4324 - val_accuracy: 0.7662 - val_loss: 0.5411
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8062 - loss: 0.4248 - val_accuracy: 0.7727 - val_loss: 0.5415
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7915 - loss: 0.4304 - val_accuracy: 0.7662 - val_loss: 0.5402
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7980 - loss: 0.4138 - val_accuracy: 0.7662 - val_loss: 0.5414
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8046 - loss: 0.4084 - val_accuracy: 0.7727 - val_loss: 0.5414
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4240 - val_accuracy: 0.7727 - val_loss: 0.5416
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4231 - val_accuracy: 0.7662 - val_loss: 0.5419
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4422 - val_accuracy: 0.7662 - val_loss: 0.5424
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4155 - val_accuracy: 0.7727 - val_loss: 0.5424
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4232 - val_accuracy: 0.7792 - val_loss: 0.5463
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.7997 - loss: 0.4194 - val_accuracy: 0.7792 - val_loss: 0.5425
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4238 - val_accuracy: 0.7597 - val_loss: 0.5451
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7834 - loss: 0.4305 - val_accuracy: 0.7662 - val_loss: 0.5450
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7899 - loss: 0.4187 - val_accuracy: 0.7662 - val_loss: 0.5444
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.8062 - loss: 0.4202 - val_accuracy: 0.7662 - val_loss: 0.5455
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7818 - loss: 0.4185 - val_accuracy: 0.7662 - val_loss: 0.5459
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7850 - loss: 0.4252 - val_accuracy: 0.7662 - val_loss: 0.5464
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8013 - loss: 0.4080 - val_accuracy: 0.7597 - val_loss: 0.5473
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7671 - loss: 0.4326 - val_accuracy: 0.7662 - val_loss: 0.5496
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8046 - loss: 0.4223 - val_accuracy: 0.7727 - val_loss: 0.5491
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8013 - loss: 0.4240 - val_accuracy: 0.7727 - val_loss: 0.5487
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7785 - loss: 0.4331 - val_accuracy: 0.7662 - val_loss: 0.5509
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8094 - loss: 0.4216 - val_accuracy: 0.7662 - val_loss: 0.5509
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.7915 - loss: 0.4111 - val_accuracy: 0.7727 - val_loss: 0.5509
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.8225 - loss: 0.4071 - val_accuracy: 0.7597 - val_loss: 0.5517
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7948 - loss: 0.4180 - val_accuracy: 0.7662 - val_loss: 0.5516
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7980 - loss: 0.4118 - val_accuracy: 0.7532 - val_loss: 0.5535
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8013 - loss: 0.4066 - val_accuracy: 0.7468 - val_loss: 0.5609
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.8029 - loss: 0.4133 - val_accuracy: 0.7403 - val_loss: 0.5626
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.8062 - loss: 0.4092 - val_accuracy: 0.7468 - val_loss: 0.5621
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7932 - loss: 0.4169 - val_accuracy: 0.7597 - val_loss: 0.5607
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8078 - loss: 0.4071 - val_accuracy: 0.7532 - val_loss: 0.5619
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8013 - loss: 0.4071 - val_accuracy: 0.7468 - val_loss: 0.5628
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4150 - val_accuracy: 0.7468 - val_loss: 0.5638
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4133 - val_accuracy: 0.7532 - val_loss: 0.5633
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8062 - loss: 0.4079 - val_accuracy: 0.7403 - val_loss: 0.5658
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4362 - val_accuracy: 0.7532 - val_loss: 0.5660
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7948 - loss: 0.4272 - val_accuracy: 0.7468 - val_loss: 0.5658
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7980 - loss: 0.4193 - val_accuracy: 0.7468 - val_loss: 0.5654
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4037 - val_accuracy: 0.7532 - val_loss: 0.5635
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8208 - loss: 0.4130 - val_accuracy: 0.7597 - val_loss: 0.5618
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8094 - loss: 0.4154 - val_accuracy: 0.7597 - val_loss: 0.5623
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7948 - loss: 0.4159 - val_accuracy: 0.7532 - val_loss: 0.5625
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8143 - loss: 0.4125 - val_accuracy: 0.7662 - val_loss: 0.5586
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.4150 - val_accuracy: 0.7532 - val_loss: 0.5580
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4098 - val_accuracy: 0.7662 - val_loss: 0.5547
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4179 - val_accuracy: 0.7662 - val_loss: 0.5584
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4041 - val_accuracy: 0.7662 - val_loss: 0.5587
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4113 - val_accuracy: 0.7662 - val_loss: 0.5578
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4093 - val_accuracy: 0.7597 - val_loss: 0.5598
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4007 - val_accuracy: 0.7662 - val_loss: 0.5637
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4115 - val_accuracy: 0.7662 - val_loss: 0.5672
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4135 - val_accuracy: 0.7662 - val_loss: 0.5683
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4094 - val_accuracy: 0.7662 - val_loss: 0.5718
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4179 - val_accuracy: 0.7468 - val_loss: 0.5734
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8046 - loss: 0.4048 - val_accuracy: 0.7468 - val_loss: 0.5730
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8094 - loss: 0.3847 - val_accuracy: 0.7532 - val_loss: 0.5734
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8176 - loss: 0.4069 - val_accuracy: 0.7597 - val_loss: 0.5729
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8046 - loss: 0.4164 - val_accuracy: 0.7468 - val_loss: 0.5747
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8094 - loss: 0.3991 - val_accuracy: 0.7403 - val_loss: 0.5721
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8046 - loss: 0.4130 - val_accuracy: 0.7468 - val_loss: 0.5718
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8013 - loss: 0.4020 - val_accuracy: 0.7468 - val_loss: 0.5741
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8208 - loss: 0.3890 - val_accuracy: 0.7597 - val_loss: 0.5763
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.3989 - val_accuracy: 0.7662 - val_loss: 0.5740
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4001 - val_accuracy: 0.7532 - val_loss: 0.5757
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.3953 - val_accuracy: 0.7532 - val_loss: 0.5798
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8029 - loss: 0.4189 - val_accuracy: 0.7403 - val_loss: 0.5801
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8225 - loss: 0.3982 - val_accuracy: 0.7597 - val_loss: 0.5806
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3888 - val_accuracy: 0.7532 - val_loss: 0.5820
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3971 - val_accuracy: 0.7597 - val_loss: 0.5814
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4075 - val_accuracy: 0.7468 - val_loss: 0.5779
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.4015 - val_accuracy: 0.7468 - val_loss: 0.5789
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8192 - loss: 0.3899 - val_accuracy: 0.7468 - val_loss: 0.5772
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8029 - loss: 0.4030 - val_accuracy: 0.7468 - val_loss: 0.5771
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8160 - loss: 0.4080 - val_accuracy: 0.7403 - val_loss: 0.5788
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8192 - loss: 0.3885 - val_accuracy: 0.7468 - val_loss: 0.5790
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8078 - loss: 0.4002 - val_accuracy: 0.7468 - val_loss: 0.5794
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8111 - loss: 0.3900 - val_accuracy: 0.7468 - val_loss: 0.5815
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8013 - loss: 0.3908 - val_accuracy: 0.7338 - val_loss: 0.5829
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8257 - loss: 0.3822 - val_accuracy: 0.7403 - val_loss: 0.5847
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8062 - loss: 0.4025 - val_accuracy: 0.7403 - val_loss: 0.5844
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3972 - val_accuracy: 0.7403 - val_loss: 0.5861
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4026 - val_accuracy: 0.7403 - val_loss: 0.5839
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3987 - val_accuracy: 0.7403 - val_loss: 0.5860
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.3940 - val_accuracy: 0.7468 - val_loss: 0.5863
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4077 - val_accuracy: 0.7597 - val_loss: 0.5850
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8257 - loss: 0.3778 - val_accuracy: 0.7597 - val_loss: 0.5855
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8013 - loss: 0.4112 - val_accuracy: 0.7597 - val_loss: 0.5851
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8241 - loss: 0.3866 - val_accuracy: 0.7597 - val_loss: 0.5853
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8160 - loss: 0.4073 - val_accuracy: 0.7597 - val_loss: 0.5841
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.8078 - loss: 0.3979 - val_accuracy: 0.7597 - val_loss: 0.5858
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.8208 - loss: 0.4016 - val_accuracy: 0.7532 - val_loss: 0.5882
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8111 - loss: 0.3930 - val_accuracy: 0.7532 - val_loss: 0.5904
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8143 - loss: 0.3985 - val_accuracy: 0.7532 - val_loss: 0.5858
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7915 - loss: 0.4014 - val_accuracy: 0.7532 - val_loss: 0.5845
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8290 - loss: 0.3868 - val_accuracy: 0.7662 - val_loss: 0.5824
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8127 - loss: 0.3915 - val_accuracy: 0.7662 - val_loss: 0.5802
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8257 - loss: 0.3928 - val_accuracy: 0.7662 - val_loss: 0.5788
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8241 - loss: 0.3855 - val_accuracy: 0.7532 - val_loss: 0.5828
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8274 - loss: 0.3926 - val_accuracy: 0.7662 - val_loss: 0.5879
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.3944 - val_accuracy: 0.7662 - val_loss: 0.5906
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3824 - val_accuracy: 0.7468 - val_loss: 0.5927
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.3959 - val_accuracy: 0.7597 - val_loss: 0.5913
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.3951 - val_accuracy: 0.7338 - val_loss: 0.5940
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3888 - val_accuracy: 0.7468 - val_loss: 0.5942
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8192 - loss: 0.3856 - val_accuracy: 0.7597 - val_loss: 0.5943
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8062 - loss: 0.3973 - val_accuracy: 0.7338 - val_loss: 0.5977
Epoch 162/200